kind: Service
apiVersion: v1
metadata:
  name: micro-report
  labels:
    app: micro-reporteport

spec:
  type: NodePort
  selector:
    app: micro-report
  ports:
  - port: 9090
    targetPort: 9090
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: micro-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-report
  template:
    metadata:
      labels:
        app: micro-report
        version: v1
    spec:
      containers:
      - name: micro-report
        image: micro-report
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
